SELECT DISTINCT
category
FROM gold.dim_products      --Dimension

SELECT DISTINCT
sales_amount
FROM gold.fact_sales       --Measure

SELECT DISTINCT
quantity
FROM gold.fact_sales       --Measure

SELECT DISTINCT
product_name
FROM gold.dim_products      --Dimension

SELECT DISTINCT
birthdate
FROM gold.dim_customers    --Dimension

SELECT DISTINCT
DATEDIFF(year, birthdate, GETDATE()) AS Avg_Age   --measure(it should be numerice and makes sense to aggregate)
FROM gold.dim_customers 

SELECT DISTINCT
customer_id
FROM gold.dim_customers    --Dimension

--Explore ALL objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

--Explore ALL Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

--Dimension Exploration
--Explore All countries our customers come from.
SELECT DISTINCT country FROM gold.dim_customers

--Explore  All categories "the Major Division"
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1,2,3

--Date Explorations
--find the date of the first and last order

SELECT MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date,
DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years
FROM gold.fact_sales

--Find the youngest and the oldest customer
SELECT 
MIN(birthdate) AS oldest_birthdate,
DATEDIFF(year, MIN (birthdate), GETDATE()) AS oldest_age,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers

--Find the Total Sales
SELECt SUM(sales_amount) AS total_sales FROM gold.fact_sales

--Find how many items are sold
SELECt SUM(quantity) AS total_qunatity FROM gold.fact_sales

--Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales

--Find the total number of Orders
SELECt COUNT(order_number) AS total_orders FROM gold.fact_sales
SELECt COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales 

--Find the total number of products 
SELECt COUNT(product_name) AS total_products FROM gold.dim_products
SELECt COUNT(DISTINCT product_name) AS total_products FROM gold.dim_products

--Find the total number of cutomers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers;

--Find the total number of cutomers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales;

--Generate a Report that shows all key metrics of the business

SELECT 'Total Sales' as measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Sales' as measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' , AVG(price) FROM gold.fact_sales
UNION ALL 
SELECT 'Total Nr. Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products', COUNT(product_name) FROM gold.dim_products
UNION ALL 
SELECT 'Total Nr. Customers', COUNT(Customer_key) FROM gold.dim_customers



--Find total customer by countries
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

--Find total customers by gender
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--Find total products by category
SELECT 
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--What is the average costs in each category?
SELECT 
category,
AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC

--What is the total revenue generated for each category?
SELECT 
p.category,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

--Find total revenue is generated by each 
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC



--What is the distribution of sold items across countries?
SELECT 
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.country
ORDER BY total_sold_items DESC


--Which 5 products generate the highest revenue?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY 
p.product_name
ORDER BY total_revenue DESC

--What are the 5 worst- performing products in terms of sales?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY 
p.product_name
ORDER BY total_revenue 

--Find the top 10 customers who have generated the highest revenue
SELECT top 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- the 3 customers with the fewest orders placed

SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders

/* Other analysis */
SELECT 
YEAR(order_date) AS order_year,
MONTH(order_date) AS order_year,
SUM(sales_amount) AS total_sales,
COUNT(DISTINCT customer_key) as total_customers,
SUM(quantity) as total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY YEAR(order_date), MONTH(order_date)


SELECT 
DATETRUNC(month, order_date) AS order_date,
SUM(sales_amount) AS total_sales,
COUNT(DISTINCT customer_key) as total_customers,
SUM(quantity) as total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month, order_date)
ORDER BY DATETRUNC(month, order_date)


--Cumulative analysis
--calculate the total sales per month
--and the running total of sales over time

SELECT 
order_date,
total_sales,
SUM(total_sales) OVER (PARTITION BY order_date ORDER BY order_date) AS running_total_sales
FROM
(
SELECT 
DATETRUNC(month, order_date) AS order_date,
SUM(sales_amount) AS total_sales
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month, order_date)
) t


--performance analysis
/*Analyse the yearly perfromance of products by comparing their sales 
to both the average sales performance of the product and the previous years's sales*/
WITH yearly_product_sales AS(
SELECT 
YEAR(f.order_date) AS order_year,
p.product_name,
SUM(f.sales_amount) AS current_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
WHERE f.order_date IS NOT NULL
GROUP BY
YEAR(f.order_date),
p.product_name
)
SELECT
order_year,
product_name,
current_sales,
AVG(current_sales) OVER (PARTITION BY product_name) avg_sales,
current_sales - AVG(current_sales) OVER (partition by product_name) AS diff_avg,
CASE WHEN current_sales - AVG(current_sales) OVER (partition by product_name) > 0 THEN 'Above Avg'
WHEN current_sales - AVG(current_sales) OVER (partition by product_name) < 0 THEN 'below Avg'
ELSE 'avg'
END avg_change,
LAG (current_sales) OVER (PARTITION BY product_name ORDER BY order_year) py_sales,
current_sales - LAG(current_sales) OVER (partition by product_name ORDER BY order_year) AS diff_py,
CASE WHEN current_sales - AVG(current_sales) OVER (partition by product_name) > 0 THEN 'Increase'
WHEN current_sales - AVG(current_sales) OVER (partition by product_name) < 0 THEN 'Decrease'
ELSE 'No Change'
END py_change,
current_sales - LAG (current_sales) OVER (PARTITION BY product_name ORDER BY order_year) AS diff_py
FROM yearly_product_sales
ORDER BY product_name, order_year



--Part - to - Whole (proportional analysis) 
--Which categories contribute the most to overall sales?
WITH category_sales AS(
SELECT 
category,
SUM(sales_amount) total_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p 
ON p.product_key = f.product_key
GROUP BY category)

SELECT
category,
total_sales,
SUM(total_sales) OVER () overall_sales,
CONCAT(ROUND((CAST( total_sales AS FLOAT) /SUM(total_sales) OVER ())* 100, 2), '%') AS percentage_of_total
FROM category_sales
ORDER BY total_sales DESC


--Data Segmentation
/* Segemnt products into cost ranges and 
count how many products fall into each segment */
WITH product_segments AS (
SELECT 
product_key,
product_name,
cost,
CASE WHEN cost < 100 THEN 'Below 100'
WHEN cost BETWEEN 100 AND 500 THEN '100-500'
WHEN cost BETWEEN 500 AND 1000 '500-1000'
ELSE 'above 1000'
END cost_range
FROM gold.dim_products)

SELECT 
cost_range,
COUNT(product_key) AS total_products 
FROM product_segments
GROUP BY cost_range
ORDER BY total_products DESC



/* Group customers into three segments based on their spending behavior:
-VIP : customers with at least 12 months of history but spending more than 5,000.
-Regular : customers with a lifespan less than 12 months of history but spending 5,000 or less.
-New : customers with a lifespan less than 12 months.
And find the total number of customers by each group
*/
WITH customer_spending AS (
SELECT 
c.customer_key,
SUM(f.sales_amount) AS total_spending,
MIN(order_date) AS first_order,
MAX(order_date) AS last_order,
DATEDIFF(month, MIN(order_date), MAX(order_date)) AS lifespan
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c 
ON f.customer_key = c.customer_key
GROUP BY c.customer_key
)
SELECT 
customer_segment,
COUNT(customer_key) AS total_customers
FROM(
SELECT 
customer_key,

CASE WHEN lifespan >= 12 AND total_spending > 10000 THEN 'VIP'
WHEN lifespan > = 12 AND total_spending <= 10000 THEN 'REGULAR'
ELSE 'New'
END customer_segment
FROM customer_spending) t
GROUP BY customer_segment
order by total_customers DESC

