SELECT DISTINCT
category
FROM gold.dim_products      --Dimension

SELECT DISTINCT
sales_amount
FROM gold.fact_sales       --Measure

SELECT DISTINCT
quantity
FROM gold.fact_sales       --Measure

SELECT DISTINCT
product_name
FROM gold.dim_products      --Dimension

SELECT DISTINCT
birthdate
FROM gold.dim_customers    --Dimension

SELECT DISTINCT
DATEDIFF(year, birthdate, GETDATE()) AS Avg_Age   --measure(it should be numerice and makes sense to aggregate)
FROM gold.dim_customers 

SELECT DISTINCT
customer_id
FROM gold.dim_customers    --Dimension

--Explore ALL objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

--Explore ALL Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

--Dimension Exploration
--Explore All countries our customers come from.
SELECT DISTINCT country FROM gold.dim_customers

--Explore  All categories "the Major Division"
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1,2,3

--Date Explorations
--find the date of the first and last order

SELECT MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date,
DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years
FROM gold.fact_sales

--Find the youngest and the oldest customer
SELECT 
MIN(birthdate) AS oldest_birthdate,
DATEDIFF(year, MIN (birthdate), GETDATE()) AS oldest_age,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers

--Find the Total Sales
SELECt SUM(sales_amount) AS total_sales FROM gold.fact_sales

--Find how many items are sold
SELECt SUM(quantity) AS total_qunatity FROM gold.fact_sales

--Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales

--Find the total number of Orders
SELECt COUNT(order_number) AS total_orders FROM gold.fact_sales
SELECt COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales 

--Find the total number of products 
SELECt COUNT(product_name) AS total_products FROM gold.dim_products
SELECt COUNT(DISTINCT product_name) AS total_products FROM gold.dim_products

--Find the total number of cutomers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers;

--Find the total number of cutomers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales;

--Generate a Report that shows all key metrics of the business

SELECT 'Total Sales' as measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Sales' as measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' , AVG(price) FROM gold.fact_sales
UNION ALL 
SELECT 'Total Nr. Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products', COUNT(product_name) FROM gold.dim_products
UNION ALL 
SELECT 'Total Nr. Customers', COUNT(Customer_key) FROM gold.dim_customers



--Find total customer by countries
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

--Find total customers by gender
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--Find total products by category
SELECT 
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--What is the average costs in each category?
SELECT 
category,
AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC

--What is the total revenue generated for each category?
SELECT 
p.category,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

--Find total revenue is generated by each 
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC



--What is the distribution of sold items across countries?
SELECT 
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.country
ORDER BY total_sold_items DESC


--Which 5 products generate the highest revenue?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY 
p.product_name
ORDER BY total_revenue DESC

--What are the 5 worst- performing products in terms of sales?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY 
p.product_name
ORDER BY total_revenue 

--Find the top 10 customers who have generated the highest revenue
SELECT top 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- the 3 customers with the fewest orders placed

SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders
